// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: audit_log.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordAuditLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`                         // Name of the calling service (e.g. "order-service", "product-service")
	ActorId       int64                  `protobuf:"varint,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`         // ID of the actor (merchant or customer)
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`                               // Role of the actor (e.g. "MERCHANT", "CUSTOMER", "SYSTEM")
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                 // Description of the action (includes action, resource, and extra context)
	OccurredAt    string                 `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"` // Actual event time as ISO 8601 string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordAuditLogRequest) Reset() {
	*x = RecordAuditLogRequest{}
	mi := &file_audit_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordAuditLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordAuditLogRequest) ProtoMessage() {}

func (x *RecordAuditLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordAuditLogRequest.ProtoReflect.Descriptor instead.
func (*RecordAuditLogRequest) Descriptor() ([]byte, []int) {
	return file_audit_log_proto_rawDescGZIP(), []int{0}
}

func (x *RecordAuditLogRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *RecordAuditLogRequest) GetActorId() int64 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

func (x *RecordAuditLogRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RecordAuditLogRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RecordAuditLogRequest) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

type RecordAuditLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // ID of the newly created log entry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordAuditLogResponse) Reset() {
	*x = RecordAuditLogResponse{}
	mi := &file_audit_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordAuditLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordAuditLogResponse) ProtoMessage() {}

func (x *RecordAuditLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordAuditLogResponse.ProtoReflect.Descriptor instead.
func (*RecordAuditLogResponse) Descriptor() ([]byte, []int) {
	return file_audit_log_proto_rawDescGZIP(), []int{1}
}

func (x *RecordAuditLogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RecordAuditLogResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type AuditLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"` // Name of the calling service
	ActorId       int64                  `protobuf:"varint,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	OccurredAt    string                 `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"` // ISO 8601 string, actual time the event occurred
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`    // ISO 8601 string
	PreviousHash  string                 `protobuf:"bytes,8,opt,name=previous_hash,json=previousHash,proto3" json:"previous_hash,omitempty"`
	CurrentHash   string                 `protobuf:"bytes,9,opt,name=current_hash,json=currentHash,proto3" json:"current_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLog) Reset() {
	*x = AuditLog{}
	mi := &file_audit_log_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLog) ProtoMessage() {}

func (x *AuditLog) ProtoReflect() protoreflect.Message {
	mi := &file_audit_log_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLog.ProtoReflect.Descriptor instead.
func (*AuditLog) Descriptor() ([]byte, []int) {
	return file_audit_log_proto_rawDescGZIP(), []int{2}
}

func (x *AuditLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditLog) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *AuditLog) GetActorId() int64 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

func (x *AuditLog) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AuditLog) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AuditLog) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *AuditLog) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AuditLog) GetPreviousHash() string {
	if x != nil {
		return x.PreviousHash
	}
	return ""
}

func (x *AuditLog) GetCurrentHash() string {
	if x != nil {
		return x.CurrentHash
	}
	return ""
}

type QueryAuditLogsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActorId         *int64                 `protobuf:"varint,1,opt,name=actor_id,json=actorId,proto3,oneof" json:"actor_id,omitempty"`
	Service         *string                `protobuf:"bytes,2,opt,name=service,proto3,oneof" json:"service,omitempty"` // Filter by calling service name
	Role            *string                `protobuf:"bytes,3,opt,name=role,proto3,oneof" json:"role,omitempty"`
	StartTime       *string                `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3,oneof" json:"start_time,omitempty"`                     // ISO 8601 string, filter by created_at (log write time, inclusive)
	EndTime         *string                `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`                           // ISO 8601 string, filter by created_at (log write time, inclusive)
	OccurredAtStart *string                `protobuf:"bytes,6,opt,name=occurred_at_start,json=occurredAtStart,proto3,oneof" json:"occurred_at_start,omitempty"` // ISO 8601 string, filter by occurred_at (event time, inclusive)
	OccurredAtEnd   *string                `protobuf:"bytes,7,opt,name=occurred_at_end,json=occurredAtEnd,proto3,oneof" json:"occurred_at_end,omitempty"`       // ISO 8601 string, filter by occurred_at (event time, inclusive)
	Limit           int32                  `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`                                                   // Page size
	Offset          int32                  `protobuf:"varint,9,opt,name=offset,proto3" json:"offset,omitempty"`                                                 // Offset for pagination
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryAuditLogsRequest) Reset() {
	*x = QueryAuditLogsRequest{}
	mi := &file_audit_log_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAuditLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAuditLogsRequest) ProtoMessage() {}

func (x *QueryAuditLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_log_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAuditLogsRequest.ProtoReflect.Descriptor instead.
func (*QueryAuditLogsRequest) Descriptor() ([]byte, []int) {
	return file_audit_log_proto_rawDescGZIP(), []int{3}
}

func (x *QueryAuditLogsRequest) GetActorId() int64 {
	if x != nil && x.ActorId != nil {
		return *x.ActorId
	}
	return 0
}

func (x *QueryAuditLogsRequest) GetService() string {
	if x != nil && x.Service != nil {
		return *x.Service
	}
	return ""
}

func (x *QueryAuditLogsRequest) GetRole() string {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return ""
}

func (x *QueryAuditLogsRequest) GetStartTime() string {
	if x != nil && x.StartTime != nil {
		return *x.StartTime
	}
	return ""
}

func (x *QueryAuditLogsRequest) GetEndTime() string {
	if x != nil && x.EndTime != nil {
		return *x.EndTime
	}
	return ""
}

func (x *QueryAuditLogsRequest) GetOccurredAtStart() string {
	if x != nil && x.OccurredAtStart != nil {
		return *x.OccurredAtStart
	}
	return ""
}

func (x *QueryAuditLogsRequest) GetOccurredAtEnd() string {
	if x != nil && x.OccurredAtEnd != nil {
		return *x.OccurredAtEnd
	}
	return ""
}

func (x *QueryAuditLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryAuditLogsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type QueryAuditLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*AuditLog            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAuditLogsResponse) Reset() {
	*x = QueryAuditLogsResponse{}
	mi := &file_audit_log_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAuditLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAuditLogsResponse) ProtoMessage() {}

func (x *QueryAuditLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_log_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAuditLogsResponse.ProtoReflect.Descriptor instead.
func (*QueryAuditLogsResponse) Descriptor() ([]byte, []int) {
	return file_audit_log_proto_rawDescGZIP(), []int{4}
}

func (x *QueryAuditLogsResponse) GetLogs() []*AuditLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *QueryAuditLogsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type VerifyAuditLogChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *string                `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3,oneof" json:"start_time,omitempty"` // ISO 8601 string
	EndTime       *string                `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`       // ISO 8601 string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAuditLogChainRequest) Reset() {
	*x = VerifyAuditLogChainRequest{}
	mi := &file_audit_log_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAuditLogChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAuditLogChainRequest) ProtoMessage() {}

func (x *VerifyAuditLogChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_log_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAuditLogChainRequest.ProtoReflect.Descriptor instead.
func (*VerifyAuditLogChainRequest) Descriptor() ([]byte, []int) {
	return file_audit_log_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyAuditLogChainRequest) GetStartTime() string {
	if x != nil && x.StartTime != nil {
		return *x.StartTime
	}
	return ""
}

func (x *VerifyAuditLogChainRequest) GetEndTime() string {
	if x != nil && x.EndTime != nil {
		return *x.EndTime
	}
	return ""
}

type VerifyAuditLogChainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	FailedLogId   string                 `protobuf:"bytes,2,opt,name=failed_log_id,json=failedLogId,proto3" json:"failed_log_id,omitempty"` // If verification fails, the ID of the log entry where the chain is broken or tampered
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                              // Error details or success message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAuditLogChainResponse) Reset() {
	*x = VerifyAuditLogChainResponse{}
	mi := &file_audit_log_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAuditLogChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAuditLogChainResponse) ProtoMessage() {}

func (x *VerifyAuditLogChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_log_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAuditLogChainResponse.ProtoReflect.Descriptor instead.
func (*VerifyAuditLogChainResponse) Descriptor() ([]byte, []int) {
	return file_audit_log_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyAuditLogChainResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *VerifyAuditLogChainResponse) GetFailedLogId() string {
	if x != nil {
		return x.FailedLogId
	}
	return ""
}

func (x *VerifyAuditLogChainResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_audit_log_proto protoreflect.FileDescriptor

const file_audit_log_proto_rawDesc = "" +
	"\n" +
	"\x0faudit_log.proto\x12\x0fceramicraft.log\"\xa3\x01\n" +
	"\x15RecordAuditLogRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\x03R\aactorId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1f\n" +
	"\voccurred_at\x18\x05 \x01(\tR\n" +
	"occurredAt\"M\n" +
	"\x16RecordAuditLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\"\x8d\x02\n" +
	"\bAuditLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\x03R\aactorId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1f\n" +
	"\voccurred_at\x18\x06 \x01(\tR\n" +
	"occurredAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12#\n" +
	"\rprevious_hash\x18\b \x01(\tR\fpreviousHash\x12!\n" +
	"\fcurrent_hash\x18\t \x01(\tR\vcurrentHash\"\xa7\x03\n" +
	"\x15QueryAuditLogsRequest\x12\x1e\n" +
	"\bactor_id\x18\x01 \x01(\x03H\x00R\aactorId\x88\x01\x01\x12\x1d\n" +
	"\aservice\x18\x02 \x01(\tH\x01R\aservice\x88\x01\x01\x12\x17\n" +
	"\x04role\x18\x03 \x01(\tH\x02R\x04role\x88\x01\x01\x12\"\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tH\x03R\tstartTime\x88\x01\x01\x12\x1e\n" +
	"\bend_time\x18\x05 \x01(\tH\x04R\aendTime\x88\x01\x01\x12/\n" +
	"\x11occurred_at_start\x18\x06 \x01(\tH\x05R\x0foccurredAtStart\x88\x01\x01\x12+\n" +
	"\x0foccurred_at_end\x18\a \x01(\tH\x06R\roccurredAtEnd\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\b \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\t \x01(\x05R\x06offsetB\v\n" +
	"\t_actor_idB\n" +
	"\n" +
	"\b_serviceB\a\n" +
	"\x05_roleB\r\n" +
	"\v_start_timeB\v\n" +
	"\t_end_timeB\x14\n" +
	"\x12_occurred_at_startB\x12\n" +
	"\x10_occurred_at_end\"h\n" +
	"\x16QueryAuditLogsResponse\x12-\n" +
	"\x04logs\x18\x01 \x03(\v2\x19.ceramicraft.log.AuditLogR\x04logs\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"|\n" +
	"\x1aVerifyAuditLogChainRequest\x12\"\n" +
	"\n" +
	"start_time\x18\x01 \x01(\tH\x00R\tstartTime\x88\x01\x01\x12\x1e\n" +
	"\bend_time\x18\x02 \x01(\tH\x01R\aendTime\x88\x01\x01B\r\n" +
	"\v_start_timeB\v\n" +
	"\t_end_time\"v\n" +
	"\x1bVerifyAuditLogChainResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12\"\n" +
	"\rfailed_log_id\x18\x02 \x01(\tR\vfailedLogId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xc9\x02\n" +
	"\x0fAuditLogService\x12a\n" +
	"\x0eRecordAuditLog\x12&.ceramicraft.log.RecordAuditLogRequest\x1a'.ceramicraft.log.RecordAuditLogResponse\x12a\n" +
	"\x0eQueryAuditLogs\x12&.ceramicraft.log.QueryAuditLogsRequest\x1a'.ceramicraft.log.QueryAuditLogsResponse\x12p\n" +
	"\x13VerifyAuditLogChain\x12+.ceramicraft.log.VerifyAuditLogChainRequest\x1a,.ceramicraft.log.VerifyAuditLogChainResponseB3Z1github.com/sw5005-sus/ceramicraft-audit-client/pbb\x06proto3"

var (
	file_audit_log_proto_rawDescOnce sync.Once
	file_audit_log_proto_rawDescData []byte
)

func file_audit_log_proto_rawDescGZIP() []byte {
	file_audit_log_proto_rawDescOnce.Do(func() {
		file_audit_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audit_log_proto_rawDesc), len(file_audit_log_proto_rawDesc)))
	})
	return file_audit_log_proto_rawDescData
}

var file_audit_log_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_audit_log_proto_goTypes = []any{
	(*RecordAuditLogRequest)(nil),       // 0: ceramicraft.log.RecordAuditLogRequest
	(*RecordAuditLogResponse)(nil),      // 1: ceramicraft.log.RecordAuditLogResponse
	(*AuditLog)(nil),                    // 2: ceramicraft.log.AuditLog
	(*QueryAuditLogsRequest)(nil),       // 3: ceramicraft.log.QueryAuditLogsRequest
	(*QueryAuditLogsResponse)(nil),      // 4: ceramicraft.log.QueryAuditLogsResponse
	(*VerifyAuditLogChainRequest)(nil),  // 5: ceramicraft.log.VerifyAuditLogChainRequest
	(*VerifyAuditLogChainResponse)(nil), // 6: ceramicraft.log.VerifyAuditLogChainResponse
}
var file_audit_log_proto_depIdxs = []int32{
	2, // 0: ceramicraft.log.QueryAuditLogsResponse.logs:type_name -> ceramicraft.log.AuditLog
	0, // 1: ceramicraft.log.AuditLogService.RecordAuditLog:input_type -> ceramicraft.log.RecordAuditLogRequest
	3, // 2: ceramicraft.log.AuditLogService.QueryAuditLogs:input_type -> ceramicraft.log.QueryAuditLogsRequest
	5, // 3: ceramicraft.log.AuditLogService.VerifyAuditLogChain:input_type -> ceramicraft.log.VerifyAuditLogChainRequest
	1, // 4: ceramicraft.log.AuditLogService.RecordAuditLog:output_type -> ceramicraft.log.RecordAuditLogResponse
	4, // 5: ceramicraft.log.AuditLogService.QueryAuditLogs:output_type -> ceramicraft.log.QueryAuditLogsResponse
	6, // 6: ceramicraft.log.AuditLogService.VerifyAuditLogChain:output_type -> ceramicraft.log.VerifyAuditLogChainResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_audit_log_proto_init() }
func file_audit_log_proto_init() {
	if File_audit_log_proto != nil {
		return
	}
	file_audit_log_proto_msgTypes[3].OneofWrappers = []any{}
	file_audit_log_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audit_log_proto_rawDesc), len(file_audit_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audit_log_proto_goTypes,
		DependencyIndexes: file_audit_log_proto_depIdxs,
		MessageInfos:      file_audit_log_proto_msgTypes,
	}.Build()
	File_audit_log_proto = out.File
	file_audit_log_proto_goTypes = nil
	file_audit_log_proto_depIdxs = nil
}
