// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: audit_log.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuditLogService_RecordAuditLog_FullMethodName      = "/ceramicraft.log.AuditLogService/RecordAuditLog"
	AuditLogService_QueryAuditLogs_FullMethodName      = "/ceramicraft.log.AuditLogService/QueryAuditLogs"
	AuditLogService_VerifyAuditLogChain_FullMethodName = "/ceramicraft.log.AuditLogService/VerifyAuditLogChain"
)

// AuditLogServiceClient is the client API for AuditLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuditLogServiceClient interface {
	RecordAuditLog(ctx context.Context, in *RecordAuditLogRequest, opts ...grpc.CallOption) (*RecordAuditLogResponse, error)
	QueryAuditLogs(ctx context.Context, in *QueryAuditLogsRequest, opts ...grpc.CallOption) (*QueryAuditLogsResponse, error)
	VerifyAuditLogChain(ctx context.Context, in *VerifyAuditLogChainRequest, opts ...grpc.CallOption) (*VerifyAuditLogChainResponse, error)
}

type auditLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditLogServiceClient(cc grpc.ClientConnInterface) AuditLogServiceClient {
	return &auditLogServiceClient{cc}
}

func (c *auditLogServiceClient) RecordAuditLog(ctx context.Context, in *RecordAuditLogRequest, opts ...grpc.CallOption) (*RecordAuditLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordAuditLogResponse)
	err := c.cc.Invoke(ctx, AuditLogService_RecordAuditLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditLogServiceClient) QueryAuditLogs(ctx context.Context, in *QueryAuditLogsRequest, opts ...grpc.CallOption) (*QueryAuditLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryAuditLogsResponse)
	err := c.cc.Invoke(ctx, AuditLogService_QueryAuditLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditLogServiceClient) VerifyAuditLogChain(ctx context.Context, in *VerifyAuditLogChainRequest, opts ...grpc.CallOption) (*VerifyAuditLogChainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyAuditLogChainResponse)
	err := c.cc.Invoke(ctx, AuditLogService_VerifyAuditLogChain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuditLogServiceServer is the server API for AuditLogService service.
// All implementations must embed UnimplementedAuditLogServiceServer
// for forward compatibility.
type AuditLogServiceServer interface {
	RecordAuditLog(context.Context, *RecordAuditLogRequest) (*RecordAuditLogResponse, error)
	QueryAuditLogs(context.Context, *QueryAuditLogsRequest) (*QueryAuditLogsResponse, error)
	VerifyAuditLogChain(context.Context, *VerifyAuditLogChainRequest) (*VerifyAuditLogChainResponse, error)
	mustEmbedUnimplementedAuditLogServiceServer()
}

// UnimplementedAuditLogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuditLogServiceServer struct{}

func (UnimplementedAuditLogServiceServer) RecordAuditLog(context.Context, *RecordAuditLogRequest) (*RecordAuditLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordAuditLog not implemented")
}
func (UnimplementedAuditLogServiceServer) QueryAuditLogs(context.Context, *QueryAuditLogsRequest) (*QueryAuditLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryAuditLogs not implemented")
}
func (UnimplementedAuditLogServiceServer) VerifyAuditLogChain(context.Context, *VerifyAuditLogChainRequest) (*VerifyAuditLogChainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyAuditLogChain not implemented")
}
func (UnimplementedAuditLogServiceServer) mustEmbedUnimplementedAuditLogServiceServer() {}
func (UnimplementedAuditLogServiceServer) testEmbeddedByValue()                         {}

// UnsafeAuditLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditLogServiceServer will
// result in compilation errors.
type UnsafeAuditLogServiceServer interface {
	mustEmbedUnimplementedAuditLogServiceServer()
}

func RegisterAuditLogServiceServer(s grpc.ServiceRegistrar, srv AuditLogServiceServer) {
	// If the following call panics, it indicates UnimplementedAuditLogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuditLogService_ServiceDesc, srv)
}

func _AuditLogService_RecordAuditLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordAuditLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditLogServiceServer).RecordAuditLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditLogService_RecordAuditLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditLogServiceServer).RecordAuditLog(ctx, req.(*RecordAuditLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditLogService_QueryAuditLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAuditLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditLogServiceServer).QueryAuditLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditLogService_QueryAuditLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditLogServiceServer).QueryAuditLogs(ctx, req.(*QueryAuditLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditLogService_VerifyAuditLogChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyAuditLogChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditLogServiceServer).VerifyAuditLogChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditLogService_VerifyAuditLogChain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditLogServiceServer).VerifyAuditLogChain(ctx, req.(*VerifyAuditLogChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuditLogService_ServiceDesc is the grpc.ServiceDesc for AuditLogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuditLogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ceramicraft.log.AuditLogService",
	HandlerType: (*AuditLogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordAuditLog",
			Handler:    _AuditLogService_RecordAuditLog_Handler,
		},
		{
			MethodName: "QueryAuditLogs",
			Handler:    _AuditLogService_QueryAuditLogs_Handler,
		},
		{
			MethodName: "VerifyAuditLogChain",
			Handler:    _AuditLogService_VerifyAuditLogChain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "audit_log.proto",
}
